### ISSUE TITLE
Affichage de la catégorie et du langage dans le tableau des scripts

### ISSUE THREAD

**Issue by NathanBnm** [NathanBnm/springboot-tds#3]
Je n'arrive pas à afficher le nom de la catégorie et du langage pour chaque ligne mais seulement l'objet. Comment puis-je faire pour afficher uniquement la catégorie ou le langage concerné @jcheron ?

![image](https://user-images.githubusercontent.com/45366162/78271131-16280400-750c-11ea-8335-962a29c4fb5a.png)

Voici comment sont affichées mes lignes dans l'élément `data-table` de Vuetify:

```html
<template v-slot:item="props">
     <tr>
          <td><% props.item.title %></td>
          <td><% props.item.category %></td>
          <td><% props.item.language %></td>
     </tr>
</template>
```

**Comment by jcheron** [comment]
`category` et `language` sont des objets, donc c'est normal.
Accédez à leur propriété à afficher:
```html
<template v-slot:item="props">
     <tr>
          <td><% props.item.title %></td>
          <td><% props.item.category.name %></td>
          <td><% props.item.language.name %></td>
     </tr>
</template>
```
