### ISSUE TITLE
Filtre sur les colonnes pour la recherche

### ISSUE THREAD

**Issue by NathanBnm** [NathanBnm/springboot-tds#4]
Je pensais pouvoir utiliser un filtre personnalisé pour pouvoir filtrer le contenu du tableau en fonction de telle ou telle colonne (activées ou non avec des cases à cocher par exemple).

J'ai trouvé quelques infos sur la documentation de Vuetify (voir https://vuetifyjs.com/en/components/data-tables/#custom-filtering) et ailleurs (voir https://github.com/frontid/vuetify-data-table-multi-filter)

Cependant je n'arrive pas à implémenter le JavaScript dans le contrôleur Java, je ne sais pas du tout ce qu'il faut modifier pour que cela fonctionne (N'ayant pas réellement appris le JavaScript c'est assez difficile).

Avez-vous des pistes / exemples qui pourraient m'aider @jcheron ? Ou bien une autre façon de faire.

**Comment by jcheron** [comment]
Vous parlez de sélectionner les membres à afficher dans la réponse, donc de l'affichage ou non de certaines colonnes.
Le plus simple:
Ajouter en vueJs (java) un data `selectedHeaders` correspondant aux colonnes à afficher, contenant par défaut la même valeur que `headers`.
Ce tableau sera modifiable par l'utilisateur, dans l'interface.
Ensuite, dans votre vue, plutôt que de faire référence à `headers`, vous faîtes réf à `selectedHeaders`.

https://github.com/NathanBnm/springboot-tds/blob/4b2b09e4ed2587d83a797e967fdc24136c722597/src/main/resources/templates/search.html#L13-L17

**Comment by NathanBnm** [comment]
@jcheron j'ai essayé d'effectuer des modifications dans le tableau mais je n'ai pas réussi je ne vois pas du tout ce qu'il faut utiliser. J'ai essayé de faire quelque chose avec des cases à cocher à l'aide de ce modèle https://codepen.io/anon/pen/jeWRvN après avoir cherché. Dans l'exemple il y a un bouton "toggle" qui permet d'afficher ou non une certaine colonne du tableau.

Cependant je ne vois pas comment utiliser le filtre pour chaque colonne, je n'arrive à le faire que pour une seule.

```java
vue.addComputed("computedHeaders", "return this.hideTitle ? this.headers.filter(header => header.value !== 'title') : this.headers;");
```

Un autre problème se pose, c'est que le fait d'enlever un entête au tableau ne retire pas le contenu de la colonne. De ce fait tous les noms de colonnes sont décalés vers la gauche. Dans mon exemple j'arrive a retirer l'entête "nom" et donc l'entête "description" se retrouve au dessus de la colonne "nom" etc.

PS: Je ne sais pas comment vous faîtes pour citer un extrait de code directement je n'ai pas réussi.

**Comment by jcheron** [comment]
Admettons que `selectedHeaders` soit défini de la façon suivante:
``` java
vue.addDataRaw("selectedHeaders", "['title','description','category','language']");
```
Les `computedHeaders`, c'est les `headers` dont le name est dans `selectedHeaders`: 

``` java
vue.addComputed("computedHeaders", "return this.headers.filter((header=>this.selectedHeaders.includes(header.value)));");
```

Et pour le problème des colonnes qui s'affichent quand même, mettez des conditions sur l'affichage des balises `<td>` dans le template:
```html
<td  v-if="selectedHeaders.includes('title')"><% props.item.title%></td>
```

PS: sur discord, dans `#support` j'ai fait une video qui montre comment faire référence à du code dans les issues
